### ISSUE TITLE
File doesn't exist during push

### ISSUE THREAD

**Issue by Olgagr** [mckn/gulp-nuget#10]
I have a problem with nuget.push on Jenkins. I get an error:

```
c:\jenkins\workspace\my_project\node_modules\gulp-nuget\lib\push.js:22
            if(err) throw new gutil.PluginError('gulp-nuget', err);
                          ^
Error: Command failed: File does not exist (c:\jenkins\workspace\my_project\stage\project.3.5.1.32.nupkg).


    at ChildProcess.exithandler (child_process.js:647:15)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:753:16)
    at Process.ChildProcess._handle.onexit (child_process.js:820:5)
```

I've checked current location before running nuget.push:

```
> pwd
/c/jenkins/workspace/my_project
```

I've checked the content of the c:\jenkins\workspace\my_project\stage directory:

```
> ls stage/
app.bundle.js
app.bundle.js.map
index.html
project.3.5.1.32.nupkg
vendor.bundle.js
vendor.bundle.js.map
web.config
```

It seems like the file is there, but nuget.push doesn't see it. What else can cause that ? For example nupkg can be invalid and the error is misleading ?

**Comment by mckn** [comment]
Hello, thanks for reporting this. I will see if I can reproduce this issue in any way. But in any way I will try to improve the error messages reported back to the user.

Thanks!
