### ISSUE TITLE
Does it work with Asp.net core ?

### ISSUE THREAD

**Issue by maxisam** [mckn/gulp-nuget#11]
It seems like it doesn't work with asp.net core ?

**Comment by mckn** [comment]
Okay, that doesnt sound so good. Do you have an example so I can try it?

**Comment by maxisam** [comment]
I just create a new project right out of "new project" with VS2015. I think because the output directory of  .net core is different from the way before, the plug in can't find the built dll to work. The new .net core output is at ./artifacts under solution folder.

**Comment by maxisam** [comment]
Actually, I just realized asp.net core has a project template that can make the project build into nuget package directly. So the problem actually doesn't really exist anymore. I just need to point the correct path for push.

**Comment by mckn** [comment]
So I can close this one?

**Comment by maxisam** [comment]
yes, thx
