### ISSUE TITLE
Delete command

### ISSUE THREAD

**Issue by diazrm** [mckn/gulp-nuget#14]
Would be nice to add the functionality for delete command

**Comment by mckn** [comment]
Hello,

Thanks for the suggestion! Do you have an example on how this would be used in your build script?

Best regards!

**Comment by diazrm** [comment]
My pack-and-push task is something like:

```
var thisBundleSuffix = 'Common';
var packageJson = require('../../package.json');

gulp.task('pack-and-push-' + thisBundleSuffix, ['unpublish-' + thisBundleSuffix], function () {
    require('../../gulp-functions/packAndPush.js')(gulp, thisBundleSuffix, packageJson);
});

gulp.task('unpublish-' + thisBundleSuffix, function (cb) {
    require('../../gulp-functions/deletePackage.js')(thisBundleSuffix, packageJson, cb);
});
```
And then, the unpublish task calls a delete function:

```
module.exports = function deletePackage(bundleSuffix, packageJson, cb) {
    var command = packageJson.nugetExePath + ' delete Com.Gyf.WebCore.' + bundleSuffix + ' ' + packageJson.extendedVersion + ' -Source ' + packageJson.nugetSource;
    exec(command, function (err, stdout, stderr) {
        cb();
    });
};
```
The latter translates to:

`nuget.exe delete Com.Gyf.WebCore.SomePackage 1.x.x -Source http://myprivatepackagesrepo.com`

Note that I need to pass a callback to the delete function due to the paralellism of Gulp. As far as I don't have a delete command, I've lost the ability to chain the commands in a serial manner.

Tell me if you need extra info about the code I've ommited in sake of simplicity (e.g.: details about the package.json custom properties).

**Comment by mckn** [comment]
Hmm..okay..but why do u want to unpublish a old package? To save space on the server?

**Comment by diazrm** [comment]
No, that's not the case. Actually, we keep the historical versions live in the private repo, due to the dependencies in other systems that don't need the newer versions.
The main use case for deleting a package is when you found issues related to the deployment itself. Things like a mistaken dependency, libs you forgot to include, typos or errors in your nuspec or even bugs that reveal once the package is deployed in a target solution. In fewer words: you need to fix something in your nuget but don't want (or need) to change the version pattern.

**Comment by mckn** [comment]
Do not have any plans to support this command as I do not see a good case when you want to use this feature.
