### ISSUE TITLE
UNIX Support

### ISSUE THREAD

**Issue by artbelov** [mckn/gulp-nuget#18]
Hello @mckn!

It would be great if you would add support packing on UNIX with using [Mono](http://www.mono-project.com/).

*Example for Grunt - https://github.com/spatools/grunt-nuget/blob/3ea24a762255d82dca3ae1fd2446b3d3f77ab3e7/libs/nuget.js#L32*

---

Best Regards, Artem.

**Comment by mckn** [comment]
This should work since the docker image that is running at Travis CI is running the tests with mono. What kind of issues do you experience?
