### ISSUE TITLE
NuGet restore command support

### ISSUE THREAD

**Issue by ybelouad** [mckn/gulp-nuget#2]
In order to build server, i have to run the nuget restore command before running.
It would be really great if gulp-nuget adds support for this command.

Docs:
http://docs.nuget.org/docs/reference/package-restore
http://blogs.msdn.com/b/dotnet/archive/2013/08/22/improved-package-restore.aspx

**Comment by bbaia** [comment]
+1

**Comment by TimMurphy** [comment]
These is [gulp-nuget-restore](https://www.npmjs.com/package/gulp-nuget-restore). Does that allow this issue to be closed?

**Comment by mckn** [comment]
I will add this support in the new rewritten version of the gulp-nuget package.

**Comment by mckn** [comment]
Should be resolved in new version 1.0.0
