### ISSUE TITLE
Gulp-nuget depends on a deleted NPM package

### ISSUE THREAD

**Issue by alistairmgreen** [mckn/gulp-nuget#20]
The shrink wrap file for `gulp-nuget` specifies a dependency on `ansi-styles@2.2.0`.

That particular version has just disappeared from npm, so it is no longer possible to run `npm install` on any project that uses `gulp-nuget`. Consequently, my build which was working fine yesterday is now broken.

This can be fixed by upgrading to `ansi-styles@2.2.1` which is still valid.

**Comment by dejoost** [comment]
this is also breaking our ci builds....

**Comment by limeybastow** [comment]
Same problem here although oddly, 2.2.0 seems to have been unpublished in March, 2016 according to the following issue in ansi-styles - https://github.com/chalk/ansi-styles/issues/15

**Comment by kamran-pervaiz** [comment]
I was just going to create a new question as i was not sure why my build starting failing all of a sudden. could you please fix it? angular cli is using gulp-nuget

**Comment by alistairmgreen** [comment]
To get my build working again, I simply uninstalled gulp-nuget then copied and pasted the relevant bits of its source code into my gulpfile. (I only needed the restore command, which is a small subset of what gulp-nuget does.)

**Comment by aromine** [comment]
Creating this npm-shrinkwrap.json worked for me
`{  
   "dependencies":{  
      "gulp-nuget":{  
         "version":"1.0.3",
         "from":"gulp-nuget@1.0.3",
         "dependencies":{  
            "gulp-util":{  
               "version":"3.0.8",
               "from":"gulp-util@3.0.8",
               "dependencies":{  
                  "chalk":{  
                     "from":"chalk@1.1.3",
                     "version":"1.1.3",
                     "dependencies":{  
                        "ansi-styles":{  
                           "version":"2.2.1",
                           "from":"ansi-styles@2.1.0"
                        }
                     }
                  }
               }
            }
         }
      }
   }
}`

**Comment by dejoost** [comment]
I started using yarn https://yarnpkg.com instead of npm to restore the dependencies, this seems to work for now....

**Comment by kamran-pervaiz** [comment]
@aromine could you please explain a bit how to use npm-shrinkwrap.json file?

**Comment by mckn** [comment]
Hello, sorry for being late on responding on this issue. I am on vacation an do not have any computer with me. I will be back the 18th of July and will merge this fix asap. Sorry again for the delay.

**Comment by kamran-pervaiz** [comment]
@mckn I figured thats why i emailed you from my hotmail, so that people dont panick :)
