### ISSUE TITLE
Unable to install gulp-nuget from internal repository

### ISSUE THREAD

**Issue by bvamos** [mckn/gulp-nuget#23]
Your package-lock file is part of th epackage and in the resolved fields there are absolute URLs to npmjs.org. With this setting I am unable to install this package using an internal repository behind a firewall , as npm goes directly to npmjs.org to download the dependencies.
I guess it would be fine to use relative path in resolved fields.

**Comment by mckn** [comment]
I guess this is an issue with npm rather then this package?
