### ISSUE TITLE
Gulp-util is deprecated

### ISSUE THREAD

**Issue by NielsDM** [mckn/gulp-nuget#28]
**Problem**
Within the company we use Gulp-nuget to publish our packages.
When we install Gulp-nuget security issues are raised because of the reference to Gulp-util.
**Solution**
If I went trought this code I saw some easy fixes to lose the dependency to Gulp-util.
I want to update this code.
But I'm quite hesitant because the last update to this project is from 2018.
I want to verify if you would look into the pull request and publish to npmjs.com?

**Comment by mckn** [comment]
Yes, feel free to open a PR and I will merge and publish a new version of the package. Thanks for pinging me about this 🙏🏻

**Comment by mckn** [comment]
Closed by #29

**Comment by NielsDM** [comment]
@mckn Thank you for the swift implementation of this!
Very much appreciated.
