### ISSUE TITLE
nuget.pack creates 2 output .nupkg files

### ISSUE THREAD

**Issue by NightOwl888** [mckn/gulp-nuget#8]
I am using the following command, but it creates 2 `.nupkg` files - one at the location I specify and another one in the root directory of my project. Both files have the same name (which corresponds to {basename}.nupkg). I checked and it doesn't seem to have anything to do with the location of the `.nuspec` file or the location of `nuget.exe`.

Here is the code that I am using. It uses [gulp-out](https://www.npmjs.com/package/gulp-out).

```js
var distributionFolder = './dist/';
var nuspecFile = './project.nuspec';
var nugetPath = '/nuget.exe';
var version = '1.0.0';

gulp.src('', { base: './' })
	.pipe(nuget.pack({ nuspec: nuspecFile, nuget: nugetPath, version: version }))
	.pipe(out(distributionFolder + '{basename}.nupkg'));
```

**Comment by mckn** [comment]
Should be resolved in new version 1.0.0
